title: HiRISEAI
name: HiRISEAI
author: Ping Wang
description:
logo: 'assets/images/logo.png'
favicon: 'favicon.ico'
keywords: [HiRISE, AI]
baseurl: ""
url: "https://hiriseai.github.io"



# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""


  

# The shortname for your Disqus site to enable comments.
disqus:

# Colors
accent_color: '#2d72d9'

# Site footer


plugins:
  - jekyll-paginate



paginate: 8
paginate_path: '/page:num/'


# Permalinks
permalink: pretty

# Conversion
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
